image: node:latest

before_script:
  - npm install -g typescript
  - npm install

cache:
  paths:
  - node_modules/

stages:
  - build

build_and_test:
  stage: build
  script:
    - tsc
    - npm test
