image: node:latest

before_script:
  - npm install -g typescript
  - npm install

cache:
  paths:
  - node_modules/

stages:
  - build
  - test

building:
  stage: build
  script:
    - tsc

testing:
  stage: test
  script:
    - npm test